AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - test-app/**/*
  NewCops: enable
  SuggestExtensions: false

# Mistakes were made, not that interested in changing the public API, though.
Metrics/ParameterLists:
  Max: 7

# This has to match the gem name.
Naming/FileName:
  Exclude:
    - lib/prawn-rails-forms.rb

# Public docs are sufficient (for now).
Style/Documentation:
  Enabled: false
