AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - test-app/**/*

# Public docs are sufficient (for now).
Style/Documentation:
  Enabled: false

# I don't see the benefit of blacklisting an entire language feature.
Style/ParallelAssignment:
  Enabled: false

