source 'https://rubygems.org'

gem 'rails', '~> 5.1'
gem 'prawn-rails-forms', path: '../'
gem 'puma', '~> 4.3'

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'pry-byebug'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end
